### ISSUE TITLE
Add/Verify MacOS support

### ISSUE THREAD

**Issue by zekrom-vale** [zekrom-vale/electron-quick-start#59]
**All macOS support is untested and experimental**

Currently, the macOS support is a fragment of the old application template.  It is not guaranteed to work as it has not been tested.  This is because as of right now macOS Electron applications cannot be created on Windows devices.  https://www.electron.build/multi-platform-build.html  I also do not have access to macOS at the moment and I have no reason to.  If anyone wants to add support feel free to submit a pull request.

**Comment by zekrom-vale** [comment]
As expected things fail:
```bash
Wrote new app to: ElectronShinyApp/electron-quick-start-linux-x64
> electron-quick-start@2.1.1 package-mac
> node scripts/darwin.js
Experamental and untested: Things may break
Please submit all issues to https://github.com/zekrom-vale/electron-quick-start/issues/59
Note: I have no plan on fixing issues for MacOS at this point
/Users/runner/work/shinyElectron/shinyElectron/ElectronShinyApp/electron-quick-start-darwin-x64
electron-packager . electron-quick-start --overwrite --platform=darwin --arch=x64 --out=ElectronShinyApp --icon=assets/icons/png/1024x1024.png --prune=true --version-string.CompanyName=None --version-string.FileDescription=CE --version-string.ProductName=Shiny Electron App --ignore="R-Portable-*|R-Portable-(Linux|Win)|\.git.*|\.Rhistory|.*\.Rproj|scripts|ElectronShinyApp"
Packaging app for platform darwin x64 using electron v29.1.5
WARNING: Could not find icon "assets/icons/png/1024x1024.icns", not updating app icon
Wrote new app to: ElectronShinyApp/electron-quick-start-darwin-x64
node:fs:1634
  const stats = binding.lstat(
                        ^
Error: Error: ENOENT: no such file or directory, lstat '/Users/runner/work/shinyElectron/shinyElectron/ElectronShinyApp/electron-quick-start-darwin-x64/resources/app/config'
    at Object.lstatSync (node:fs:1634:25)
    at Object.lstatSync (/Users/runner/work/shinyElectron/shinyElectron/node_modules/graceful-fs/polyfills.js:318:34)
    at statFunc (/Users/runner/work/shinyElectron/shinyElectron/node_modules/fs-extra/lib/util/stat.js:24:20)
    at getStatsSync (/Users/runner/work/shinyElectron/shinyElectron/node_modules/fs-extra/lib/util/stat.js:25:19)
    at Object.checkPathsSync (/Users/runner/work/shinyElectron/shinyElectron/node_modules/fs-extra/lib/util/stat.js:64:33)
    at Object.copySync (/Users/runner/work/shinyElectron/shinyElectron/node_modules/fs-extra/lib/copy/copy-sync.js:27:38)
    at start (/Users/runner/work/shinyElectron/shinyElectron/scripts/core.js:36:6)
    at Object.<anonymous> (/Users/runner/work/shinyElectron/shinyElectron/scripts/darwin.js:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/Users/runner/work/shinyElectron/shinyElectron/ElectronShinyApp/electron-quick-start-darwin-x64/resources/app/config'
}
Node.js v20.12.0
Error: Process completed with exit code 1.
```

**Comment by zekrom-vale** [comment]
macOS tests are passing, just need someone to try it.

**Comment by agdamsbo** [comment]
Hi. I am trying to just build the default app on my M1 mac with macOS 15.3.1. I have downloaded the R-Portable-Mac from the repository, put it in the project root, and followed the steps. When I run `sudo npm run package-mac`, I get the following message:
```
> shinyElectron@3.0.0 package-mac
> node scripts/darwin.js

Experamental and untested: Things may break
Please submit all issues to https://github.com/zekrom-vale/electron-quick-start/issues/59
Note: I have no plan on fixing issues for MacOS at this point
/Volumes/FREESEARCHR/FreesearchR/FreesearchR-electron/ElectronShinyApp/shinyElectron-darwin-x64/shinyElectron.app
electron-packager . shinyElectron --overwrite --platform=darwin --arch=x64 --out=ElectronShinyApp --icon=assets/icons/png/1024x1024.png --prune=true --version-string.CompanyName=None --version-string.FileDescription=CE --version-string.ProductName=Shiny Electron App --ignore="R-Portable-*|R-Portable-(Linux|Win)|\.git.*|\.Rhistory|.*\.Rproj|scripts|ElectronShinyApp"
WARNING: Could not find icon "assets/icons/png/1024x1024.icns", not updating app icon
(node:53803) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:53803) [DEP0055] DeprecationWarning: The `util.isRegExp` API is deprecated. Please use `arg instanceof RegExp` instead.
(node:53803) [DEP0047] DeprecationWarning: The `util.isDate` API is deprecated.  Please use `arg instanceof Date` instead.
```

When I try to open the app, it attempts, but eventually fails with the following pop-up:

![Image](https://github.com/user-attachments/assets/4caf811a-2c85-45b2-86cd-6390240eafb6)

I have R 4.4.1 on the machine, while the R-Portable is 4.1.2.

Any ideas on how to get this working? Thank you in advance!

I am very happy working in R, but JS is new to me.
